sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - node
matrix:
  include:
    - node_js: node
      env: TEST_BROWSERS=true
script: npm run-script ci
deploy:
  provider: npm
  email: mike@cousins.io
  api_key:
    secure: KU4JnOVGfo1v9PN/r3EBV0ZGAi+J7jqQJ2UVNJ6Por4logFGHZlWiXy25wBzip8WC1TZ+V7zJZoms9AZU1lp0khSTCPIEVDkBInYQWPtcUQSdB++rbySkcBUNqS6o4+ipZuN2Pl+IdDiFgPCC6z1hwTW9nyjyhKnj+ocD+lg0BLPFRpq8JCbYEF78kt2AYJ4CtCU5kb/QjanWkKwizzkGthcAZmEzPhA64JvutQm6itBpNyDcL9rz5xrTvqx8D81udB9kjqXpzr3uLtoHkjp2NMEbCZ+XdCVFD2AyRgdwwM9b0UfsY6/1pXSjdkJjArpPN/ja/jMzW/7a+FTMeh5m0lYzu1rn45p9mKZPL5FzbcHC4Rz5pPzpEghtKN2aNkpELMiAKGVtx+aJMCb0VJx2Y+7TjH+6AXPrzeNwL6dvcKxgo9hG3nQBp8FZn082TuW8J6KZ7FZK75m0Dg7X5LzczW2nh4tqb6SHp1wiqgafnOjsJi85JQv63LZ5M6+T7Jqjo7JffacclVkeweJf6FWLlqlo8bDIZoFEYDvcpIX8dBZqwPd8fLN/kjrFI++djZ9wysIyMNYq2it0DEglh+r2ikuWm3p5d5/v4my3Z3pv+kAJLrSqGB5aGBIZe768MHTI4j4S3sIY5CQ5Ib7zZKnQ80FOwKvkABOND56RlYsLcs=
  on:
    node: node
    tags: true
    condition: $TEST_BROWSERS = true
    all_branches: true
env:
  global:
  - secure: lnke90GUdQ1uSveYJvsJ8Pm4WO3CMR2Q3Tlxi/JDU2Ut6Cd/GaqxH7CLr+i5ZhlQ5sVII3MS0ct5NtVKDMA+gGhWzMCwddHGprkEuJi1q67oZRW8DNdBnBD2YdYrrIPspcjBOhdbUtcHNZ2sKSqX7ZiGNo7d9CPnv+PET49W07MfkUKyV+NtLccEvk/mlyVuhUJzdo6gLiYnF6GQuBbptu498iHnMThQzPUBbrKKvc0wTEUQKHafm1ltkw58J3+KdhzOcwUsBcf0v5bxxDClA98DpiR5QE6pYwCIrsAeRgkXEjESUzNa5SqIbG8YFPGG1bA4n/yD4ya+Fa25yH50sQsUZbhlEWAnyQGYe2KkFM5fSxhlEWWdUvGnHS9Oe2na2MsrEzB/Q7tr3y65TwiJniwC+Bx/RJa8SackC2TmlfR5G92mM1UgPs6LHScIUmlM+WSS3tKfZW1gLTCX5GSq3v+AmbAKlgNye7Owt3juDECoU4x/jcnPN/XIrXL9TeYQZXdx1j6rnCd+43a1g2LwA1RA2thEnp6MuQtlr0tz/x9xLN61UjcFGgRyyNnE6qaGB/owDoV0ZFVp2gky6GGFggZvc1RFvt30DLJQVTViLJbXjuWdrBiXbVb0TlDkBxFY1feWelmIczkz3xZi65tGGtP3w/Zw8TmJC06f2bnR9PA=
  - secure: RRs8ifGdpBLG0TbzETGuB0kBq8kKBJ/tVVFivsESJ2I5spi0iH0ZMEOIHFNKdzCn32QaYGn2tl3edXwQZDIrHvZJr2e3sHIUOoMycLny3YTSN2wO6rRmLCVEZokoEHS4shNB+XLrxP8O+MwXlu5Kq2iFs6M3T3FMKzY7K3DmOUwErAYiAcFk4oA0fkDGzRJSEFG2VSIchaES8/FwsOoVPCA915kA01a/8gmougxgXAAbM027KS1pmObGalccJzDFUKa2nUpWsH9rTq+YdIOgQPjxix+AiolSrBoolG5WgH+ywAn5hKnhuxMPiXLYA1xEbtW/fCDUHpILoP3QbOxrocopspM9prtCZ0zBbVNeXODcc9iaRf9sIqrBA4SXzT8OJJhL5uMbgW4wFopGmE8Gd9w3ug8jRp4IBOs9cx1Vzf56SOmBgN8t8j0VWD68MTQFakZbbChEywob4RZMMDZQMn+ZNBp4QJp/w9Aw9NhyK4HyvX892nu6QHP8kLlUYJPlah3yykMHV03r0UFwHRwtV0Wmepqipe1DsHQaDJWd3hMi7wjkVrQxvRCVL1A0xcdTcG8GWke1zqIa7Jq7vla2ZJUdjy6Z0CZcFXWQlnXzxTowypODX+iJQ0V2z+5EabGeHJ7YYAz4J6yP1MOLd7LE2xoBnSiD1AwK4jslLZoaXH8=
