ui: mocha-bdd
browsers:
  - name: chrome
    version: -1..latest
  - name: safari
    version: -1..8
  - name: firefox
    version: -1..latest
  - name: ie
    version: -1..latest
browserify:
  - transform: babelify
  - require: babelify/polyfill.js
    entry: true
